{
 "title": "Intel Core GPU Exporter",
 "tags": [
  "iGPU",
  "Metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "iGPU Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "igpu_power_gpu{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_power_gpu{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU RC6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_rc6{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU RC6",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_rc6{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Interrupt",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "irq/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_interrupts{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Interrupt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "irq/s" } },
   "targets": [
    {
     "expr": "igpu_interrupts{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Period",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_period{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Period",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "igpu_period{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Power Package",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "igpu_power_package{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Power Package",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_power_package{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "iGPU Frequency Actual",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Frequency Actual",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rotghz" } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Frequency Requested",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_frequency_requested{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU Frequency Requested",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "igpu_frequency_requested{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Render 3D", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Render 3D Wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_wait{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Render 3D Busy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_busy{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Render 3D Sema",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_sema{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Video 0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Video 0 Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_0_wait{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video 0 Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_0_busy{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video 0 Sema",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_0_sema{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Video Enhance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Video Enhance 0 Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_0_wait{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Enhance 0 Sema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_0_sema{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Enhance 0 busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_0_busy{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Blitter Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_blitter_0_wait{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blitter Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_blitter_0_busy{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blitter Sema",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_blitter_0_sema{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}